### ISSUE TITLE
Replace "create pile" key for clay to Shift + Ctrl + Right-click

### ISSUE THREAD

**Issue by Craluminum2413** [FlyingSpaten/stonepiles#3]
[Example](https://github.com/anegostudios/vssurvivalmod/blob/9f2f42da65ac74d1aff50f480c6c38769c87890a/Item/ItemHoe.cs#L53-L57)

**Comment by FlyingSpaten** [comment]
The Shift+Ctrl+Right Click is currently the only working way to place a claypile.
